/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface KeyRecord {
    durationDays: bigint;
    expiryTimestamp: bigint;
    createdAt: bigint;
    keyValue: string;
    boundDeviceId?: string;
}
export interface ValidationResult {
    expiryTimestamp?: bigint;
    valid: boolean;
    message: string;
    isAdmin: boolean;
}
export interface backendInterface {
    clearAllKeys(adminKey: string): Promise<boolean>;
    deleteKey(adminKey: string, keyValue: string): Promise<boolean>;
    generateKey(adminKey: string, durationDays: bigint): Promise<string>;
    getKeys(adminKey: string): Promise<Array<KeyRecord>>;
    validateAndBindKey(keyValue: string, deviceId: string): Promise<ValidationResult>;
}
import type { KeyRecord as _KeyRecord, ValidationResult as _ValidationResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async clearAllKeys(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAllKeys(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAllKeys(arg0);
            return result;
        }
    }
    async deleteKey(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteKey(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteKey(arg0, arg1);
            return result;
        }
    }
    async generateKey(arg0: string, arg1: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateKey(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateKey(arg0, arg1);
            return result;
        }
    }
    async getKeys(arg0: string): Promise<Array<KeyRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getKeys(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKeys(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async validateAndBindKey(arg0: string, arg1: string): Promise<ValidationResult> {
        if (this.processError) {
            try {
                const result = await this.actor.validateAndBindKey(arg0, arg1);
                return from_candid_ValidationResult_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateAndBindKey(arg0, arg1);
            return from_candid_ValidationResult_n5(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_KeyRecord_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _KeyRecord): KeyRecord {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_ValidationResult_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ValidationResult): ValidationResult {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    durationDays: bigint;
    expiryTimestamp: bigint;
    createdAt: bigint;
    keyValue: string;
    boundDeviceId: [] | [string];
}): {
    durationDays: bigint;
    expiryTimestamp: bigint;
    createdAt: bigint;
    keyValue: string;
    boundDeviceId?: string;
} {
    return {
        durationDays: value.durationDays,
        expiryTimestamp: value.expiryTimestamp,
        createdAt: value.createdAt,
        keyValue: value.keyValue,
        boundDeviceId: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.boundDeviceId))
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    expiryTimestamp: [] | [bigint];
    valid: boolean;
    message: string;
    isAdmin: boolean;
}): {
    expiryTimestamp?: bigint;
    valid: boolean;
    message: string;
    isAdmin: boolean;
} {
    return {
        expiryTimestamp: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.expiryTimestamp)),
        valid: value.valid,
        message: value.message,
        isAdmin: value.isAdmin
    };
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_KeyRecord>): Array<KeyRecord> {
    return value.map((x)=>from_candid_KeyRecord_n2(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
